name: Needs and depends on example

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo output
        run: echo "First job output"
      - name: Set output
        run: echo "::set-output name=output::First job output"

  second-job:
    runs-on: ubuntu-latest
    #needs: first-job
    steps:
      - name: Echo output
        run: echo "Second job output"
      - name: Get output from first job
        run: echo ${{ needs.first-job.outputs.output }}

  third-job:
    runs-on: ubuntu-latest
   # depends on: first-job
    steps:
      - name: Echo output
        run: echo "Third job output"
